site_tourneur_fraiseur:
    resource: "@SiteTourneurFraiseurBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

user_one_registration:
    path:  /register/Candidat
    defaults: { _controller: SiteUserBundle:Default:Candidat }

user_two_registration:
    path:  /register/Recruteur
    defaults: { _controller: SiteUserBundle:Default:Recruteur }    
    
user_three_registration:
    path:  /register/Employeur
    defaults: { _controller: SiteUserBundle:Default:Employeur }    

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile