<?php
// src/Site/TourneurFraiseurBundle/Repository/AnnonceRepository.php

namespace Site\TourneurFraiseurBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	function getDerniereAnnonce(){
		
		$qb=$this->createQueryBuilder('c');
		
		$qb	->join('c.site','s')
			->where('s.idSiteemploi = :id')
			->setParameter('id',15)
			->andWhere('c.suspension = :nb')
			->setParameter('nb',10)	
			->andWhere('c.datepublication > :date')
			->setParameter('date',new \DateTime('-2 month'))	
			->orderBy('c.datepublication','DESC')
			->setMaxResults(5);
		
		return $qb->getQuery()->getResult();
	}
	
	function getAnnonce(){
		
		$qb=$this->createQueryBuilder('c');
		
		$qb	->join('c.site','s')
			->where('s.idSiteemploi = :id')
			->setParameter('id',15)
			->andWhere('c.suspension = :nb')
			->setParameter('nb',10)	
			->andWhere('c.datepublication > :date')
			->setParameter('date',new \DateTime('-2 month'))	
			->orderBy('c.datepublication','DESC');
		
		return $qb->getQuery()->getResult();
	}
	
	function getDepartement($id){
		$qb=$this->createQueryBuilder('c');
		
		$qb	->join('c.site','s')
			->where('s.idSiteemploi = :id')
			->setParameter('id',15)
			->andWhere('c.suspension = :nb')
			->setParameter('nb',10)	
			->andWhere('c.datepublication > :date')
			->setParameter('date',new \DateTime('-2 month'))	
			->orderBy('c.datepublication','DESC')
			->andWhere('c.idDepartement = :idDep')
			->setParameter('idDep',$id)	
			;
		
		return $qb->getQuery()->getResult();
	}
}
