<?php
// src/Site/TourneurFraiseurBundle/Repository/AnnonceRepository.php

namespace Site\TourneurFraiseurBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
	function getDerniereAnnonce(){
		
		$qb=$this->createQueryBuilder('c');
		
		$qb	->join('c.site','s')
			->where('s.idSiteemploi = :id')
			->setParameter('id',15)	
			->orderBy('c.datepublication','DESC')
			->setMaxResults(5);
		
		return $qb->getQuery()->getResult();
	}
	
	function getAnnonce(){
		
		$qb=$this->createQueryBuilder('c');
		
		$qb	->join('c.site','s')
			->where('s.idSiteemploi = :id')
			->setParameter('id',15)	
			->orderBy('c.datepublication','DESC');
		
		return $qb->getQuery()->getResult();
	}
	
	function getDepartement($id){
		$qb=$this->createQueryBuilder('s');
		
		$qb	
			->where('s.idDepartement = :id')
			->setParameter('id',$id)	
			->orderBy('s.datepublication','DESC');
		
		return $qb->getQuery()->getResult();
	}
}
