<?php
// src/Site/TourneurFraiseurBundle/Repository/CandidatRepository.php

namespace Site\TourneurFraiseurBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
	function getDernierCandidat(){
		$qb=$this->createQueryBuilder('a');
		$qb->orderBy('a.id','DESC')
			->join('a.Sy_annonce','annonce')
			->join('annonce.site','s')
			->join('s.idSiteemploi','site')
			->where('site.id = :ss')	
			->setParameter('ss', 15)	
			->setMaxResults(5);
			
		
		return $qb->getQuery()->getResult();
	}
	
	function getCVThequeTrie($dept)
	{
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.nom','ASC')
			->join('a.annonce','annonce')
			->join('annonce.site','s')
			->join('s.idSiteemploi','site')
			->where('site.id = :ss')	
			->setParameter('ss', 15)	
				;
			
			if($dept != null){
				$qb->join('a.codePostal','v')
					->join('v.departement','d')
					->where('d.id = :dept')
					->setParameter('dept', $dept);
			}
			
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCandidatFonction($candidat,$fonction){
		$qb = $this->createQueryBuilder('c');
		$qb 
			->where('c.id = :id')
			->setParameter('id', $candidat)
			->join('c.fonction','f')
			->andWhere('f.id = :fonction')
			->setParameter('fonction', $fonction)	
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCVThequeByFonction($id){
		$qb = $this->createQueryBuilder('c');
		$qb->orderBy('c.nom','ASC')
			->join('c.annonce','a')
			->join('a.site','s')
			->where('s.idFonction = :id')
			->setParameter('id', $id);
		
		return $qb
				->getQuery()->getResult();
				
	}
	
}
