<?php
// src/Site/TourneurFraiseurBundle/Repository/CandidatRepository.php

namespace Site\TourneurFraiseurBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
	function getDernierCandidat(){
		$qb=$this->createQueryBuilder('c');
		$qb->orderBy('c.datecreation','DESC')
			->setMaxResults(5);
		
		return $qb->getQuery()->getResult();
	}
	
}
