<?php
// src/Site/TourneurFraiseurBundle/Repository/CandidatRepository.php

namespace Site\TourneurFraiseurBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
	function getDernierCandidat(){
		$qb=$this->createQueryBuilder('c');
		$qb->orderBy('c.datecreation','DESC')
			->setMaxResults(5);
		
		return $qb->getQuery()->getResult();
	}
	
	function getCVThequeTrie($site,$dept)
	{
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.nom','ASC')
			->join('a.annonce','annonce')
				;
			
			if($site != null && $dept != null){
				$qb->join('annonce.site','s')
					->join('s.idSiteemploi','site')
					->where('site.id = :ss')	
					->setParameter('ss', $site)
					->join('a.codePostal','v')
					->join('v.departement','d')
					->AndWhere('d.id = :dept')
					->setParameter('dept', $dept);
			}else{
				if($site != null){
				$qb->join('annonce.site','s')
					->join('s.idSiteemploi','site')
					->where('site.id = :ss')	
					->setParameter('ss', $site);
				}

				if($dept != null){
					$qb->join('a.codePostal','v')
						->join('v.departement','d')
						->where('d.id = :dept')
						->setParameter('dept', $dept);
				}
			}
		
		return $qb
				->getQuery()
				->getResult();
	}
	
	function getCandidatFonction($candidat,$fonction){
		$qb = $this->createQueryBuilder('c');
		$qb 
			->where('c.id = :id')
			->setParameter('id', $candidat)
			->join('c.fonction','f')
			->andWhere('f.id = :fonction')
			->setParameter('fonction', $fonction)	
			;
		
		
		return $qb
				->getQuery()
				->getResult();
	}
	
}
