<?php
// src/Site/TourneurFraiseurBundle/Repository/SiteRepository.php

namespace Site\TourneurFraiseurBundle\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{
	function getSiteNom(){
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.intitulesiteemploi','ASC')
				
			;
		
		
		return $qb;
				
	}
	
	function getSite(){
		
		$qb = $this->createQueryBuilder('a');
		$qb
			->orderBy('a.id','ASC')
			;
		
		return $qb;
	}
	
	function getSiteTri(){
		$qb = $this->createQueryBuilder('a');
		$qb 
			->orderBy('a.domaine','ASC')
				
			;
		
		
		return $qb;
				
	}
	
}
?>